## **Students Marks Analyzer**
### Create a NumPy array of marks for 5 students in 3 subjects.

### **Find:**

### Total marks of each student

### Average marks

### Highest scorer

### Subject-wise average

In [11]:
import numpy as np
marks = np.array([
    [78, 85, 90],
    [67, 72, 70],
    [90, 92, 88],
    [56, 60, 65],
    [80, 75, 85]
])
print(marks)

[[78 85 90]
 [67 72 70]
 [90 92 88]
 [56 60 65]
 [80 75 85]]


In [12]:
# total marks of each student
b = np.sum(marks,axis=1)
print("Total marks of student 1 :",b[0])
print("Total marks of student 2 :",b[1])
print("Total marks of student 3 :",b[2])
print("Total marks of student 4 :",b[3])
print("Total marks of student 5 :",b[4])

Total marks of student 1 : 253
Total marks of student 2 : 209
Total marks of student 3 : 270
Total marks of student 4 : 181
Total marks of student 5 : 240


In [13]:
# average marks
c = np.mean(marks,axis=1)
print("Average marks of student 1 :",c[0])
print("Average marks of student 2 :",c[1])
print("Average marks of student 3 :",c[2])
print("Average marks of student 4 :",c[3])
print("Average marks of student 5 :",c[4])

Average marks of student 1 : 84.33333333333333
Average marks of student 2 : 69.66666666666667
Average marks of student 3 : 90.0
Average marks of student 4 : 60.333333333333336
Average marks of student 5 : 80.0


In [15]:
# highest scorer
d = np.argmax(b)
print("Highest scorer is student", d + 1)

Highest scorer is student 3


In [16]:
# subject wise average
e = np.mean(marks,axis=0)
print("Average marks of subject 1:",e[0])
print("Average marks of subject 2:",e[1])
print("Average marks of subject 3:",e[2])

Average marks of subject 1: 74.2
Average marks of subject 2: 76.8
Average marks of subject 3: 79.6


## **Weather Temperature Analysis**
### Store temperatures of 7 days.

### **Find**:

### Hottest day

### Coldest day

### Average temperature

### Days above average

In [17]:
import numpy as np
temp = np.array([32, 35, 30, 31, 36, 38, 33])
print(temp)

[32 35 30 31 36 38 33]


In [26]:
# hotest day
print("Hotest day :",np.argmax(temp)+1,"with a temp of",np.max(temp))

Hotest day : 6 with a temp of 38


In [27]:
# coldest day
print("Coldest day :",np.argmin(temp)+1,"with a temp of",np.min(temp))

Coldest day : 3 with a temp of 30


In [28]:
# average temperature
print("Average temperature:",np.mean(temp))

Average temperature: 33.57142857142857


In [29]:
# days above average
print(temp[temp>np.mean(temp)])

[35 36 38]


## **Image Brightness Controller**
### Represent a grayscale image using a NumPy matrix.
### Increase brightness by 50.

In [30]:
import numpy as np
image = np.array([
    [50, 80, 100],
    [120, 150, 200],
    [30, 60, 90]
])
bright = image + 50
print(bright)

[[100 130 150]
 [170 200 250]
 [ 80 110 140]]


## **Matrix Multiplication Calculator**
### Multiply two matrices using NumPy.

In [31]:
import numpy as np
a = np.array([
    [1, 2],
    [3, 4]
])
b = np.array([
    [5, 6],
    [7, 8]
])
result=np.matmul(a,b)
print(result)

[[19 22]
 [43 50]]


## **Random Password Number Generator**
### Generate 10 random numbers from 1000 to 9999.

In [33]:
import numpy as np
for x in range(0,10):
  print(np.random.randint(1000,10000))

6874
8984
1553
3810
8485
5194
3406
1583
4009
7197


In [35]:
import numpy as np
passwords = np.random.randint(1000,10000,10)
print(passwords)

[3519 4577 9388 9379 4462 5341 4537 6147 6371 8688]


## **Sales Data Analysis**
### A shop records sales for 4 weeks.
### **Find:**

### Total sales

### Best week

### Worst week

In [36]:
import numpy as np
sales = np.array([12000, 15000, 11000, 18000])
print(sales)

[12000 15000 11000 18000]


In [37]:
# total sales
print("Total Sales:",np.sum(sales))

Total Sales: 56000


In [38]:
# best week
print("Best week:",np.argmax(sales)+1)

Best week: 4


In [40]:
# worst week
print("Worst week:",np.argmin(sales)+1)

Worst week: 3


## **AI/ML Style Dataset Normalization**
### Normalize values between 0 and 1.


In [44]:
import numpy as np
data = np.array([10, 20, 30, 40, 50])
normalised = (data-np.min(data))/(np.max(data)-np.min(data))
print(normalised)

[0.   0.25 0.5  0.75 1.  ]


## **Attendance Checker**
### 1 means Present
### 0 means Absent
### **Find:**
### Total present days
### Attendance percentage

In [50]:
import numpy as np
attendance = np.array([1,1,0,1,1,0,1])
present = np.sum(attendance)
print("Total Present Days :",present)
percentage=(present/len(attendance))*100
print("Attendance Percentage :",percentage)

Total Present Days : 5
Attendance Percentage : 71.42857142857143


## **Array Pattern Project**
### Create this pattern using NumPy.

### [[1 1 1 1 1]

### [1 0 0 0 1]

### [1 0 9 0 1]

### [1 0 0 0 1]

### [1 1 1 1 1]]

In [53]:
import numpy as np
a=np.ones((5,5),dtype='int32')
print(a)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [54]:
b=np.zeros((3,3),dtype='int32')
print(b)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [55]:
b[1,1]=9
print(b)

[[0 0 0]
 [0 9 0]
 [0 0 0]]


In [56]:
a[1:4,1:4]=b
print(a)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


## **Dice Simulation**
### Simulate rolling a dice 20 times.

### Count how many times each number appears.

In [61]:
import numpy as np
dice=np.random.randint(1,7,20)
print("dice roll for 20 times:",dice)
count=np.bincount(dice)
print("count of how many times each no appeared:",count[1:])

dice roll for 20 times: [4 5 6 6 6 2 2 4 6 1 1 3 4 3 2 4 4 5 4 1]
count of how many times each no appeared: [3 3 2 6 2 4]
