PyTorch is a Python library for Deep Learning, used to build, train, and deploy neural networks.

### **Installation**

pip install torch torchvision torchaudio

where :

torch: Core math engine. Build neural networks. Process text or numbers.

torchvision: Enables to Work with image and video datasets.

torchaudio: Enables to Work with sound.


In [ ]:
import torch
print(torch.__version__)

2.11.0+cu128


In [ ]:
print(torch.cuda.is_available())
print(torch.cuda.get_device_name(0))

True
Tesla T4


### **1. Tensors**
* A tensor is a multi-dimensional array used by PyTorch to store and process data for deep learning.
* Why are tensors used instead of Python lists or Numpy array?
Faster computation,
GPU support,
Automatic gradient computation.
* Images, Videos, Audio, Text and numerical data are all converted into tensors before being processed by a neural network.



### 1a) Types of Tensors :

In [ ]:
# 0d tensor
d0 = torch.tensor(25)
print(d0)

tensor(25)


In [ ]:
# 1d tensor
d1 = torch.tensor([1,2,3])
print(d1)

tensor([1, 2, 3])


In [ ]:
# 2d tensor
d2 = torch.tensor([[1,2,3],[4,5,6]])
print(d2)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [ ]:
# 3d tensor
d3 = torch.tensor([[[0,1,2],[3,4,5]],[[6,7,8],[9,10,11]]])
print(d3)

tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]])


In [ ]:
# 4d tensor
d4 = torch.tensor([[[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]])
print(d4)

tensor([[[[ 1,  2,  3],
          [ 4,  5,  6]],

         [[ 7,  8,  9],
          [10, 11, 12]]]])


### 1b) Tensor basics :

In [ ]:
print(type(d0))
print(type(d4))

<class 'torch.Tensor'>
<class 'torch.Tensor'>


In [ ]:
# tensor of zeroes
a = torch.zeros(5,dtype=torch.int32)
b = torch.zeros(2,3)
print(a)
print(b)

tensor([0, 0, 0, 0, 0], dtype=torch.int32)
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [ ]:
# tensor of ones
a = torch.ones(5)
b = torch.ones((3,4))
print(a)
print(b)

tensor([1., 1., 1., 1., 1.])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [ ]:
# tensor of random numbers - generate nos between 0 and 1
a = torch.rand(2,2,2,3)
print(a)

tensor([[[[0.1375, 0.3600, 0.3048],
          [0.1873, 0.4058, 0.3719]],

         [[0.5534, 0.4629, 0.5228],
          [0.5419, 0.3435, 0.4228]]],


        [[[0.1169, 0.6872, 0.4414],
          [0.7203, 0.4480, 0.4882]],

         [[0.9282, 0.6096, 0.0757],
          [0.5261, 0.9759, 0.9207]]]])


In [ ]:
# tensor of random integers - generate nos between min and max
a = torch.randint(-5,5,(2,3)) ### here -5min 5max (2,3)shape
print(a)

tensor([[ 1,  0, -1],
        [ 0,  2,  4]])


In [ ]:
# create using arange() - just like python range
a = torch.arange(1,6)
print(a)

tensor([1, 2, 3, 4, 5])


In [ ]:
# create using linspace() - evenly spaced values
a = torch.linspace(1,10,5)
print(a)

tensor([ 1.0000,  3.2500,  5.5000,  7.7500, 10.0000])


In [ ]:
# identity matrix
i = torch.eye(3)
print(i)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [ ]:
# empty tensor - random garbage vals, memory is allocated but values are uninitialized
e = torch.empty(2)
print(e)

tensor([22779.9688,     0.0000])


### 1c) Tensor properties

In [ ]:
# shape
print(d0.shape)
print(d1.shape)
print(d2.shape)
print(d3.shape)
print(d4.shape)

torch.Size([])
torch.Size([3])
torch.Size([2, 3])
torch.Size([2, 2, 3])
torch.Size([1, 2, 2, 3])


In [ ]:
# size() -- Same information as shape.
print(d0.size())
print(d1.size())
print(d2.size())
print(d3.size())
print(d4.size())

torch.Size([])
torch.Size([3])
torch.Size([2, 3])
torch.Size([2, 2, 3])
torch.Size([1, 2, 2, 3])


In [ ]:
# ndim -- number of dimensions
print(d0.ndim)
print(d1.ndim)
print(d2.ndim)
print(d3.ndim)
print(d4.ndim)

0
1
2
3
4


In [ ]:
# dtype
a = torch.tensor([1.2,1])
print(a)
print(a.dtype)
print(d1.dtype)

tensor([1.2000, 1.0000])
torch.float32
torch.int64


In [ ]:
# numel() - number of elements
print(a.numel())
print(d0.numel())
print(d1.numel())
print(d2.numel())
print(d3.numel())
print(d4.numel())

2
1
3
6
12
12


In [ ]:
# convert data type
print(a)
a = a.int()
print(a)

tensor([1.2000, 1.0000])
tensor([1, 1], dtype=torch.int32)


In [ ]:
# device -- shows where the tensor is stored
print(d0.device)

cpu


Selecting a T4 GPU runtime only makes a GPU available. To actually use it, the model and tensors must be explicitly moved to the GPU using .to("cuda") (or .to(device)). Otherwise, computations continue on the CPU.

In [ ]:
device = torch.device("cuda")
d0 = d0.to(device)
print(d0.device)

cuda:0


### 1d) Tensor Operations

In [ ]:
# addition
a1 = torch.tensor([1,2,3])
a2 = torch.tensor([1,2,3])
print(a1+a2)

tensor([2, 4, 6])


In [ ]:
# subtraction
print(a1-a2)

tensor([0, 0, 0])


In [ ]:
# multiplication
print(a1*a2)

tensor([1, 4, 9])


In [ ]:
# division
print(a1/a2)

tensor([1., 1., 1.])


In [ ]:
# matrix multiplication
m1 = torch.tensor([[1,2],[3,4]])
m2 = torch.tensor([[10,20],[30,40]])
print(torch.matmul(m1,m2))
# print(m1 @ m2) also works same

tensor([[ 70, 100],
        [150, 220]])


In [ ]:
# scalar operations
s1 = torch.tensor([1,2,3])
print(s1+5)
print(s1-5)
print(s1*5)
print(s1/5)
print(s1**5)

tensor([6, 7, 8])
tensor([-4, -3, -2])
tensor([ 5, 10, 15])
tensor([0.2000, 0.4000, 0.6000])
tensor([  1,  32, 243])


In [ ]:
# square root
print(torch.sqrt(s1))

tensor([1.0000, 1.4142, 1.7321])


In [ ]:
# sum
print(torch.sum(s1))

tensor(6)


In [ ]:
# mean
print(torch.mean(s1.float())) # works only with float val tensors

tensor(2.)


In [ ]:
# max and min
print(torch.max(s1))
print(torch.min(s1))

tensor(3)
tensor(1)


### 1e) Tensor indexing, slicing and reshaping

In [ ]:
t = torch.tensor([[10,20,30],[40,50,60]])

In [ ]:
# tensor indexing
print(t[0,0])
print(t[1,2])

tensor(10)
tensor(60)


In [ ]:
# row indexing
print(t[0])
print(t[1])

tensor([10, 20, 30])
tensor([40, 50, 60])


In [ ]:
# column indexing
print(t[:,0])
print(t[1,:])
print(t[[0,1],:])

tensor([10, 40])
tensor([40, 50, 60])
tensor([[10, 20, 30],
        [40, 50, 60]])


In [ ]:
# slicing
t1 = torch.tensor([1,2,3,4,5,6,7,8])
print(t1[:3]) ## same as fromstart to 3-1(2)
print(t1[3:]) ## from 3index to len(t1)-1

tensor([1, 2, 3])
tensor([4, 5, 6, 7, 8])


In [ ]:
# reshape
print("before")
print(t1)
t1 = t1.reshape((2,4)) ## view() also works same to reshape()
print("after")
print(t1)

before
tensor([1, 2, 3, 4, 5, 6, 7, 8])
after
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])


In [ ]:
# squeeze() - It removes value 1 from anywhere in the shape
t2 = torch.tensor([[1,2,3]])
print(t2)
print(t2.shape)
t2 = t2.squeeze()
print(t2)
print(t2.shape)

tensor([[1, 2, 3]])
torch.Size([1, 3])
tensor([1, 2, 3])
torch.Size([3])


In [ ]:
# unsqueeze() - It adds 1 value to the shape as per index val passed
t3 = torch.tensor([1,2,3])
print("before")
print(t3)
print(t3.shape)
print("after unsqueeze(0)")
t3 = t3.unsqueeze(0)
print(t3)
print(t3.shape)
print("after unsqueeze(1)")
t3 = t3.unsqueeze(1)
print(t3)
print(t3.shape)

before
tensor([1, 2, 3])
torch.Size([3])
after unsqueeze(0)
tensor([[1, 2, 3]])
torch.Size([1, 3])
after unsqueeze(1)
tensor([[[1, 2, 3]]])
torch.Size([1, 1, 3])


In [ ]:
t3 = t3.unsqueeze(3)
print(t3)
print(t3.shape)

tensor([[[[1],
          [2],
          [3]]]])
torch.Size([1, 1, 3, 1])


### **2. AutoGrad ( Automatic Differentiation )**
Autograd automatically performs the gradient calculations that Backpropagation requires. Calling loss.backward() computes the gradients for all trainable parameters(the tensors with this parameter : requires_grad=True will be tracked to compute gradients for it), and those gradients are stored in each parameter's .grad attribute

In [ ]:
x1 = torch.tensor(2.0, requires_grad=True)
y1 = x1**2
print(y1)
y1.backward()
print(x1.grad)

tensor(4., grad_fn=<PowBackward0>)
tensor(4.)


In [ ]:
x2 = torch.tensor(3.0, requires_grad=True)
y2 = 5*x2+2
print(y2)
y2.backward()
print(x2.grad)

tensor(17., grad_fn=<AddBackward0>)
tensor(5.)


### **3. Forward Propagation (without activation function -- linear)**

In [ ]:
import torch
import torch.nn as nn
class ann(nn.Module):
  def __init__(self):
    super().__init__()
    self.fc1 = nn.Linear(3,5)
    self.fc2 = nn.Linear(5,1)
  def forward(self,x):
    x = self.fc1(x)
    x = self.fc2(x)
    return x
model = ann()
x = torch.tensor([[22.2,75.0,8.2]]) ## check note below
output = model(x)
print(output)

tensor([[-0.2250]], grad_fn=<AddmmBackward0>)


| Component | Input Type | Output Type |
|-----------|------------|-------------|
| **nn.Linear()** | Float (float32) | Float (float32) |

Note : nn.Linear() expects float tensors because weights and biases are stored as float32.


In [ ]:
print(model.fc1.weight.shape)
print(model.fc1.bias.shape)
print(model.fc2.weight.shape)
print(model.fc2.bias.shape)

torch.Size([5, 3])
torch.Size([5])
torch.Size([1, 5])
torch.Size([1])


### **4. Activation function**

In [ ]:
import torch.nn as nn
x = torch.tensor([-5,0,4,-4,7])
relu = nn.ReLU()
print(relu(x))

tensor([0, 0, 4, 0, 7])


In [ ]:
import torch.nn as nn
y = torch.tensor([[8.9,0.0,3.2]])
sigmoid = nn.Sigmoid()
print(sigmoid(y))

tensor([[0.9999, 0.5000, 0.9608]])


In [ ]:
import torch.nn as nn
z = torch.tensor([5.0,2.0,1.0])
softmax = nn.Softmax(dim=0)
print(softmax(z))

tensor([0.9362, 0.0466, 0.0171])


| Activation Function | Input Type | Output Type |
|---------------------|------------|-------------|
| ReLU | Integer or Floating-point Tensor | Same dtype as input (Integer → Integer, Float → Float) |
| Sigmoid | Integer or Floating-point Tensor | Floating-point Tensor (0 to 1) |
| Softmax | Integer or Floating-point Tensor | Floating-point Tensor (Probabilities sum to 1) |

Note: Activation functions can operate on both integer and floating-point tensors. In neural networks, they almost always receive floating-point tensors because the outputs of nn.Linear() are floating-point values.

### **5. Forward Propagation**

In [ ]:
import torch
import torch.nn as nn
class ann(nn.Module):
  def __init__(self):
    super().__init__()
    self.fc1 = nn.Linear(3,5)
    self.relu = nn.ReLU()
    self.fc2 = nn.Linear(5,1)
    self.sigmoid = nn.Sigmoid()
  def forward(self,x):
    x = self.fc1(x)
    x = self.relu(x)
    x = self.fc2(x)
    x = self.sigmoid(x)
    return x
model = ann()
x = torch.tensor([[22.2,75.0,8.2]])
output = model(x)
print(output)

tensor([[0.8102]], grad_fn=<SigmoidBackward0>)


### **6. Loss Function**

In [ ]:
import torch
import torch.nn as nn

In [ ]:
prediction = torch.tensor(7.0)
actual = torch.tensor(10.2)
mse = nn.MSELoss()
loss = mse(prediction,actual)
print(loss)

tensor(10.2400)


In [ ]:
prediction = torch.tensor([2.5])
actual = torch.tensor([1.0])
bce = nn.BCEWithLogitsLoss()
loss = bce(prediction,actual)
print(loss)

tensor(0.0789)


In [ ]:
prediction = torch.tensor([[2.5, 1.2, 0.3]])
actual = torch.tensor([1])
ce = nn.CrossEntropyLoss()
loss = ce(prediction,actual)
print(loss)

tensor(1.6245)


| Loss Function | Prediction | Actual / Target |
|---------------|------------|-----------------|
| nn.MSELoss() | Float, Same Shape | Float, Same Shape |
| nn.BCEWithLogitsLoss() | Float (Logits), 2D | Float (0.0 / 1.0), 2D |
| nn.CrossEntropyLoss() | Float (Logits), 2D | Integer, 1D |

### **7. FP until Loss function**

In [ ]:
import torch
import torch.nn as nn
class ann(nn.Module):
  def __init__(self):
    super().__init__()
    self.fc1 = nn.Linear(3,5)
    self.relu = nn.ReLU()
    self.fc2 = nn.Linear(5,3)
  def forward(self,x):
    x = self.fc1(x)
    x = self.relu(x)
    x = self.fc2(x)
    return x
model = ann()
x = torch.tensor([[2.5,1.8,3.2]])
actual = torch.tensor([1])
prediction = model(x)
print("prediction (logits) :")
print(prediction)
ce = nn.CrossEntropyLoss()
loss = ce(prediction,actual)
print("Loss:")
print(loss)

prediction (logits) :
tensor([[-0.4379,  0.8625, -0.0174]], grad_fn=<AddmmBackward0>)
Loss:
tensor(0.5231, grad_fn=<NllLossBackward0>)


| Problem Type | Hidden Layer Activation | Output Layer Activation | Loss Function |
|--------------|-------------------------|-------------------------|---------------|
| Regression | `ReLU` | None | `nn.MSELoss()` |
| Binary Classification | `ReLU` | None *(Sigmoid applied internally)* | `nn.BCEWithLogitsLoss()` |
| Multi-Class Classification | `ReLU` | None *(Softmax applied internally)* | `nn.CrossEntropyLoss()` |

Note:
- ReLU (or another activation) is still used in the hidden layers.
- sigmoid or softmax were internally applied by bce or ce loss functions so there are not mentioned in output layer

### **8. Optimizers**

Note : torch.optim.SGD() can perform Batch Gradient Descent, Mini-Batch Gradient Descent, or Stochastic Gradient Descent depending on the batch size provided by the DataLoader.

In [ ]:
import torch
import torch.nn as nn
class ann(nn.Module):
  def __init__(self):
    super().__init__()
    self.fc1 = nn.Linear(3,5)
    self.relu = nn.ReLU()
    self.fc2 = nn.Linear(5,1)
  def forward(self,x):
    x = self.fc1(x)
    x = self.relu(x)
    x = self.fc2(x)
    return x
model = ann()
bce = nn.BCEWithLogitsLoss()
optimizer = torch.optim.SGD(model.parameters(),lr=0.01)
x = torch.tensor([[2.5,1.8,3.2]])
actual = torch.tensor([[1.0]])
optimizer.zero_grad()
prediction = model(x)
loss = bce(prediction,actual)
print("loss :",loss)
loss.backward()
optimizer.step()

loss : tensor(1.2712, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)


In [ ]:
import torch
import torch.nn as nn
class ann(nn.Module):
  def __init__(self):
    super().__init__()
    self.fc1 = nn.Linear(3,5)
    self.relu = nn.ReLU()
    self.fc2 = nn.Linear(5,3)
  def forward(self,x):
    x = self.fc1(x)
    x = self.relu(x)
    x = self.fc2(x)
    return x
model = ann()
ce = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(),lr=0.01)
x = torch.tensor([[2.5,1.4,3.8]])
actual = torch.tensor([2])
optimizer.zero_grad()
prediction = model(x)
loss = ce(prediction,actual)
print("loss before :",loss)
loss.backward()
optimizer.step()
prediction = model(x)
loss = ce(prediction,actual)
print("loss after :",loss)

loss before : tensor(1.1500, grad_fn=<NllLossBackward0>)
loss after : tensor(1.0898, grad_fn=<NllLossBackward0>)


### **9. Training Loop**

In [ ]:
import torch
import torch.nn as nn
class ann(nn.Module):
  def __init__(self):
    super().__init__()
    self.fc1 = nn.Linear(3,5)
    self.relu = nn.ReLU()
    self.fc2 = nn.Linear(5,1)
  def forward(self,x):
    x = self.fc1(x)
    x = self.relu(x)
    x = self.fc2(x)
    return x
model = ann()
bce = nn.BCEWithLogitsLoss()
optimizer = torch.optim.SGD(model.parameters(),lr=0.01)
x = torch.tensor([[2.5,1.8,3.2]])
actual = torch.tensor([[1.0]])
num_epochs = 20
for epoch in range(num_epochs):
  optimizer.zero_grad()
  prediction = model(x)
  loss = bce(prediction,actual)
  loss.backward()
  optimizer.step()
  print(f"Epoch {epoch+1} : Loss = {loss.item()}")

Epoch 1 : Loss = 0.8925931453704834
Epoch 2 : Loss = 0.873215913772583
Epoch 3 : Loss = 0.8543233871459961
Epoch 4 : Loss = 0.8358653783798218
Epoch 5 : Loss = 0.8177977204322815
Epoch 6 : Loss = 0.8000814914703369
Epoch 7 : Loss = 0.7826827764511108
Epoch 8 : Loss = 0.765572190284729
Epoch 9 : Loss = 0.7487242817878723
Epoch 10 : Loss = 0.7321176528930664
Epoch 11 : Loss = 0.7157342433929443
Epoch 12 : Loss = 0.6995590925216675
Epoch 13 : Loss = 0.6835805773735046
Epoch 14 : Loss = 0.6677895188331604
Epoch 15 : Loss = 0.6521793007850647
Epoch 16 : Loss = 0.6367455720901489
Epoch 17 : Loss = 0.6214860677719116
Epoch 18 : Loss = 0.6064004898071289
Epoch 19 : Loss = 0.5914899110794067
Epoch 20 : Loss = 0.5767571926116943


### **10. TensorDataset**
TensorDataset → Combines input and target tensors into a single dataset while keeping corresponding samples paired.

In [ ]:
import torch
from torch.utils.data import TensorDataset
x = torch.tensor([
    [2.5,1.8,3.2],
    [1.2,4.5,2.7],
    [3.6,2.1,5.4],
    [6.3,7.8,1.5],
    [2.8,9.1,4.0]])
y = torch.tensor([
    [1.0],
    [0.0],
    [1.0],
    [0.0],
    [1.0]
])
dataset = TensorDataset(x,y)
print(dataset)

In [ ]:
print(len(dataset))
print(dataset[0])

5
(tensor([2.5000, 1.8000, 3.2000]), tensor([1.]))


### **11. DataLoader**
DataLoader → Loads data from a dataset in batches and optionally shuffles it during training.



In [ ]:
import torch
from torch.utils.data import TensorDataset,DataLoader
x = torch.tensor([
    [2.5,1.8,3.2],
    [1.2,4.5,2.7],
    [3.6,2.1,5.4],
    [6.3,7.8,1.5],
    [2.8,9.1,4.0]])
y = torch.tensor([
    [1.0],
    [0.0],
    [1.0],
    [0.0],
    [1.0]
])
dataset = TensorDataset(x,y)
loader = DataLoader(dataset,batch_size=2,shuffle=True)
for x,y in loader:
  print("inputs :")
  print(x)
  print("outputs :")
  print(y)

inputs :
tensor([[6.3000, 7.8000, 1.5000],
        [1.2000, 4.5000, 2.7000]])
outputs :
tensor([[0.],
        [0.]])
inputs :
tensor([[2.5000, 1.8000, 3.2000],
        [2.8000, 9.1000, 4.0000]])
outputs :
tensor([[1.],
        [1.]])
inputs :
tensor([[3.6000, 2.1000, 5.4000]])
outputs :
tensor([[1.]])


⭐ Memory Rule
* batch_size = 1 → Stochastic ( pure SGD )
* batch_size = 32/64/128... → Mini-Batch
* batch_size = Entire Dataset → Batch

In [ ]:
import torch
import torch.nn as nn
from torch.utils.data import TensorDataset,DataLoader
class ann(nn.Module):
  def __init__(self):
    super().__init__()
    self.fc1 = nn.Linear(3,5)
    self.relu = nn.ReLU()
    self.fc2 = nn.Linear(5,1)
  def forward(self,x):
    x = self.fc1(x)
    x = self.relu(x)
    x = self.fc2(x)
    return x
model = ann()
bce = nn.BCEWithLogitsLoss()
optimizer = torch.optim.SGD(model.parameters(),lr=0.01)
x = torch.tensor([
    [2.5,1.8,3.2],
    [1.2,4.5,2.7],
    [3.6,2.1,5.4],
    [6.3,7.8,1.5],
    [2.8,9.1,4.0]
])
y = torch.tensor([
    [1.0],
    [0.0],
    [1.0],
    [0.0],
    [1.0]
])
dataset = TensorDataset(x,y)
loader = DataLoader(dataset,batch_size=2,shuffle=True)
num_epochs = 20
for epoch in range(num_epochs):
  for inputs,outputs in loader:
    optimizer.zero_grad()
    prediction = model(inputs)
    loss = bce(prediction,outputs)
    loss.backward()
    optimizer.step()
  print(f"epoch {epoch+1} : Loss = {loss}")

epoch 1 : Loss = 3.2726361751556396
epoch 2 : Loss = 1.505570650100708
epoch 3 : Loss = 1.3275202512741089
epoch 4 : Loss = 1.6560018062591553
epoch 5 : Loss = 0.36947500705718994
epoch 6 : Loss = 1.0194085836410522
epoch 7 : Loss = 0.38576018810272217
epoch 8 : Loss = 0.2781420648097992
epoch 9 : Loss = 0.9172280430793762
epoch 10 : Loss = 0.6855068206787109
epoch 11 : Loss = 0.7951266169548035
epoch 12 : Loss = 0.8592207431793213
epoch 13 : Loss = 0.3829534351825714
epoch 14 : Loss = 0.3730809688568115
epoch 15 : Loss = 0.8462982177734375
epoch 16 : Loss = 0.5416333675384521
epoch 17 : Loss = 0.2506677806377411
epoch 18 : Loss = 0.811786413192749
epoch 19 : Loss = 0.3575582206249237
epoch 20 : Loss = 0.3456248342990875


### **12. Train/Validation/Test**


| Dataset | Purpose | Updates Weights? | Used When? |
| :--- | :--- | :--- | :--- |
| **Training** | Learn | ✅ Yes | Every Epoch |
| **Validation** | Check Performance | ❌ No | Every Epoch (after training) |
| **Testing** | Final Evaluation | ❌ No | Once After Training |
| **Inference** | Predict New Data | ❌ No | After Deployment |


In [ ]:
import torch
import torch.nn as nn
from torch.utils.data import random_split,TensorDataset,DataLoader
class ann(nn.Module):
  def __init__(self):
    super().__init__()
    self.fc1 = nn.Linear(3,5)
    self.relu = nn.ReLU()
    self.fc2 = nn.Linear(5,1)
  def forward(self,x):
    x = self.fc1(x)
    x = self.relu(x)
    x = self.fc2(x)
    return x
model = ann()
optimizer = torch.optim.SGD(model.parameters(),lr=0.01)
bce = nn.BCEWithLogitsLoss()
x = torch.tensor([
    [2.5,1.8,3.2],
    [1.2,4.5,2.7],
    [3.6,2.1,5.4],
    [6.3,7.8,1.5],
    [2.8,9.1,4.0],
    [5.4,2.3,1.8],
    [4.1,5.6,2.9],
    [7.2,3.5,6.4],
    [8.5,2.7,1.9],
    [3.3,6.6,5.2],
    [6.8,2.2,4.1],
    [5.7,7.4,3.8],
    [4.6,1.5,6.3],
    [8.4,5.1,2.2],
    [2.9,7.7,5.6]
])
y = torch.tensor([
    [1.0],
    [0.0],
    [1.0],
    [0.0],
    [1.0],
    [0.0],
    [1.0],
    [1.0],
    [0.0],
    [1.0],
    [1.0],
    [0.0],
    [1.0],
    [0.0],
    [1.0]
])
dataset = TensorDataset(x,y)
train, validation, test = random_split(dataset,[11,2,2]) # can use [0.8,0.1,0.1] percentage also
train_loader = DataLoader(train,batch_size=2,shuffle=True)
validation_loader = DataLoader(validation,batch_size=1,shuffle=False)
test_loader = DataLoader(test,batch_size=1,shuffle=False)
num_epochs = 20
for epoch in range(num_epochs):
  # training
  model.train()
  train_loss = 0
  for inputs,outputs in train_loader:
    optimizer.zero_grad()
    prediction = model(inputs)
    loss = bce(prediction,outputs)
    loss.backward()
    optimizer.step()
    train_loss += loss.item()
  train_loss /= len(train_loader)
  # validation
  model.eval()
  valid_loss = 0
  with torch.no_grad():
    for inputs,outputs in validation_loader:
      prediction = model(inputs)
      loss = bce(prediction,outputs)
      valid_loss += loss.item()
    valid_loss /= len(validation_loader)
  print(f"epoch {epoch+1} ")
  print("Training loss :",train_loss)
  print("Validation loss :",valid_loss)
  print("-"*40)
# testing
model.eval()
test_loss = 0
with torch.no_grad():
  for inputs,outputs in test_loader:
    prediction = model(inputs)
    loss = bce(prediction,outputs)
    test_loss += loss.item()
  test_loss /= len(test_loader)
print("Final Test Loss:",test_loss)
# inference -- new unseen data
new_data = torch.tensor([[4.9,3.1,6.5]])
model.eval()
with torch.no_grad():
  prediction = model(new_data)
  probability = torch.sigmoid(prediction)
print("Predicted class :",probability.item())

epoch 1 
Training loss : 1.0177566806475322
Validation loss : 0.7021421790122986
----------------------------------------
epoch 2 
Training loss : 0.8569754461447397
Validation loss : 0.6868882477283478
----------------------------------------
epoch 3 
Training loss : 0.7488228877385458
Validation loss : 0.6789338439702988
----------------------------------------
epoch 4 
Training loss : 0.8009568353494009
Validation loss : 0.6756603121757507
----------------------------------------
epoch 5 
Training loss : 0.7151022156079611
Validation loss : 0.6780969649553299
----------------------------------------
epoch 6 
Training loss : 0.7159478962421417
Validation loss : 0.6842092573642731
----------------------------------------
epoch 7 
Training loss : 0.6792651911576589
Validation loss : 0.6808411478996277
----------------------------------------
epoch 8 
Training loss : 0.7398189455270767
Validation loss : 0.6792651563882828
----------------------------------------
epoch 9 
Training loss :


| Stage | `model.train()` | `model.eval()` | `torch.no_grad()` |
| :--- | :---: | :---: | :---: |
| **Training** | ✅ | ❌ | ❌ |
| **Validation** | ❌ | ✅ | ✅ |
| **Testing** | ❌ | ✅ | ✅ |
| **Inference** | ❌ | ✅ | ✅ |


### **13. Regularization Techniques**

Dropout

In [ ]:
import torch
import torch.nn as nn
from torch.utils.data import random_split,TensorDataset,DataLoader
class ann(nn.Module):
  def __init__(self):
    super().__init__()
    self.fc1 = nn.Linear(3,5)
    self.relu = nn.ReLU()
    self.dropout = nn.Dropout(p=0.5) ### dropout ----
    self.fc2 = nn.Linear(5,1)
  def forward(self,x):
    x = self.fc1(x)
    x = self.relu(x)
    x = self.dropout(x)
    x = self.fc2(x)
    return x
model = ann()
optimizer = torch.optim.SGD(model.parameters(),lr=0.01)
bce = nn.BCEWithLogitsLoss()
x = torch.tensor([
    [2.5,1.8,3.2],
    [1.2,4.5,2.7],
    [3.6,2.1,5.4],
    [6.3,7.8,1.5],
    [2.8,9.1,4.0],
    [5.4,2.3,1.8],
    [4.1,5.6,2.9],
    [7.2,3.5,6.4],
    [8.5,2.7,1.9],
    [3.3,6.6,5.2],
    [6.8,2.2,4.1],
    [5.7,7.4,3.8],
    [4.6,1.5,6.3],
    [8.4,5.1,2.2],
    [2.9,7.7,5.6]
])
y = torch.tensor([
    [1.0],
    [0.0],
    [1.0],
    [0.0],
    [1.0],
    [0.0],
    [1.0],
    [1.0],
    [0.0],
    [1.0],
    [1.0],
    [0.0],
    [1.0],
    [0.0],
    [1.0]
])
dataset = TensorDataset(x,y)
train, validation, test = random_split(dataset,[11,2,2])
train_loader = DataLoader(train,batch_size=2,shuffle=True)
validation_loader = DataLoader(validation,batch_size=1,shuffle=False)
test_loader = DataLoader(test,batch_size=1,shuffle=False)
num_epochs = 20
for epoch in range(num_epochs):
  model.train()
  train_loss = 0
  for inputs,outputs in train_loader:
    optimizer.zero_grad()
    prediction = model(inputs)
    loss = bce(prediction,outputs)
    loss.backward()
    optimizer.step()
    train_loss += loss.item()
  train_loss /= len(train_loader)
  model.eval()
  valid_loss = 0
  with torch.no_grad():
    for inputs,outputs in validation_loader:
      prediction = model(inputs)
      loss = bce(prediction,outputs)
      valid_loss += loss.item()
    valid_loss /= len(validation_loader)
  print("epoch -- training loss -- validation loss")
  print(f"epoch {epoch+1} -- {train_loss} -- {valid_loss}")
  print("-"*40)
model.eval()
test_loss = 0
with torch.no_grad():
  for inputs,outputs in test_loader:
    prediction = model(inputs)
    loss = bce(prediction,outputs)
    test_loss += loss.item()
  test_loss /= len(test_loader)
print("Final Test Loss:",test_loss)
new_data = torch.tensor([[4.9,3.1,6.5]])
model.eval()
with torch.no_grad():
  prediction = model(new_data)
  probability = torch.sigmoid(prediction)
print("Predicted class :",probability.item())

epoch -- training loss -- validation loss
epoch 1 -- 0.9658378213644028 -- 0.5155906230211258
----------------------------------------
epoch -- training loss -- validation loss
epoch 2 -- 0.6731127252181371 -- 0.5122997611761093
----------------------------------------
epoch -- training loss -- validation loss
epoch 3 -- 0.7587494154771169 -- 0.5237715542316437
----------------------------------------
epoch -- training loss -- validation loss
epoch 4 -- 0.7177587648232778 -- 0.5434369444847107
----------------------------------------
epoch -- training loss -- validation loss
epoch 5 -- 0.7783764104048411 -- 0.5771238505840302
----------------------------------------
epoch -- training loss -- validation loss
epoch 6 -- 0.6653803785641988 -- 0.5846554338932037
----------------------------------------
epoch -- training loss -- validation loss
epoch 7 -- 0.6270034362872442 -- 0.5941617488861084
----------------------------------------
epoch -- training loss -- validation loss
epoch 8 -- 0.

Batch Normalization

In [ ]:
import torch
import torch.nn as nn
from torch.utils.data import random_split,TensorDataset,DataLoader
class ann(nn.Module):
  def __init__(self):
    super().__init__()
    self.fc1 = nn.Linear(3,5)
    self.bn = nn.BatchNorm1d(5) ### batch normalization ---
    self.relu = nn.ReLU()
    self.dropout = nn.Dropout(p=0.5)
    self.fc2 = nn.Linear(5,1)
  def forward(self,x):
    x = self.fc1(x)
    x = self.bn(x)
    x = self.relu(x)
    x = self.dropout(x)
    x = self.fc2(x)
    return x
model = ann()
optimizer = torch.optim.SGD(model.parameters(),lr=0.01)
bce = nn.BCEWithLogitsLoss()
x = torch.tensor([
    [2.5,1.8,3.2],
    [1.2,4.5,2.7],
    [3.6,2.1,5.4],
    [6.3,7.8,1.5],
    [2.8,9.1,4.0],
    [5.4,2.3,1.8],
    [4.1,5.6,2.9],
    [7.2,3.5,6.4],
    [8.5,2.7,1.9],
    [3.3,6.6,5.2],
    [6.8,2.2,4.1],
    [5.7,7.4,3.8],
    [4.6,1.5,6.3],
    [8.4,5.1,2.2],
    [2.9,7.7,5.6]
])
y = torch.tensor([
    [1.0],
    [0.0],
    [1.0],
    [0.0],
    [1.0],
    [0.0],
    [1.0],
    [1.0],
    [0.0],
    [1.0],
    [1.0],
    [0.0],
    [1.0],
    [0.0],
    [1.0]
])
dataset = TensorDataset(x,y)
train, validation, test = random_split(dataset,[11,2,2])
train_loader = DataLoader(train,batch_size=2,shuffle=True,drop_last=True)
validation_loader = DataLoader(validation,batch_size=1,shuffle=False)
test_loader = DataLoader(test,batch_size=1,shuffle=False)
num_epochs = 20
for epoch in range(num_epochs):
  model.train()
  train_loss = 0
  for inputs,outputs in train_loader:
    optimizer.zero_grad()
    prediction = model(inputs)
    loss = bce(prediction,outputs)
    loss.backward()
    optimizer.step()
    train_loss += loss.item()
  train_loss /= len(train_loader)
  model.eval()
  valid_loss = 0
  with torch.no_grad():
    for inputs,outputs in validation_loader:
      prediction = model(inputs)
      loss = bce(prediction,outputs)
      valid_loss += loss.item()
    valid_loss /= len(validation_loader)
  print("epoch -- training loss -- validation loss")
  print(f"epoch {epoch+1} -- {train_loss} -- {valid_loss}")
  print("-"*40)
model.eval()
test_loss = 0
with torch.no_grad():
  for inputs,outputs in test_loader:
    prediction = model(inputs)
    loss = bce(prediction,outputs)
    test_loss += loss.item()
  test_loss /= len(test_loader)
print("Final Test Loss:",test_loss)
new_data = torch.tensor([[4.9,3.1,6.5]])
model.eval()
with torch.no_grad():
  prediction = model(new_data)
  probability = torch.sigmoid(prediction)
print("Predicted class :",probability.item())

epoch -- training loss -- validation loss
epoch 1 -- 0.6532557070255279 -- 0.8563021421432495
----------------------------------------
epoch -- training loss -- validation loss
epoch 2 -- 0.6135439276695251 -- 0.8583212494850159
----------------------------------------
epoch -- training loss -- validation loss
epoch 3 -- 0.695113205909729 -- 0.8382838070392609
----------------------------------------
epoch -- training loss -- validation loss
epoch 4 -- 0.632522451877594 -- 0.8427713513374329
----------------------------------------
epoch -- training loss -- validation loss
epoch 5 -- 0.657763022184372 -- 0.8090989589691162
----------------------------------------
epoch -- training loss -- validation loss
epoch 6 -- 0.7881732940673828 -- 0.8258250653743744
----------------------------------------
epoch -- training loss -- validation loss
epoch 7 -- 0.6859237551689148 -- 0.7963985502719879
----------------------------------------
epoch -- training loss -- validation loss
epoch 8 -- 0.530

L2 Regularization

In [ ]:
import torch
import torch.nn as nn
from torch.utils.data import random_split,TensorDataset,DataLoader
class ann(nn.Module):
  def __init__(self):
    super().__init__()
    self.fc1 = nn.Linear(3,5)
    self.relu = nn.ReLU()
    self.fc2 = nn.Linear(5,1)
  def forward(self,x):
    x = self.fc1(x)
    x = self.relu(x)
    x = self.fc2(x)
    return x
model = ann()
optimizer = torch.optim.SGD(model.parameters(),lr=0.01,weight_decay=0.001) ### L2
bce = nn.BCEWithLogitsLoss()
x = torch.tensor([
    [2.5,1.8,3.2],
    [1.2,4.5,2.7],
    [3.6,2.1,5.4],
    [6.3,7.8,1.5],
    [2.8,9.1,4.0],
    [5.4,2.3,1.8],
    [4.1,5.6,2.9],
    [7.2,3.5,6.4],
    [8.5,2.7,1.9],
    [3.3,6.6,5.2],
    [6.8,2.2,4.1],
    [5.7,7.4,3.8],
    [4.6,1.5,6.3],
    [8.4,5.1,2.2],
    [2.9,7.7,5.6]
])
y = torch.tensor([
    [1.0],
    [0.0],
    [1.0],
    [0.0],
    [1.0],
    [0.0],
    [1.0],
    [1.0],
    [0.0],
    [1.0],
    [1.0],
    [0.0],
    [1.0],
    [0.0],
    [1.0]
])
dataset = TensorDataset(x,y)
train, validation, test = random_split(dataset,[11,2,2])
train_loader = DataLoader(train,batch_size=2,shuffle=True)
validation_loader = DataLoader(validation,batch_size=1,shuffle=False)
test_loader = DataLoader(test,batch_size=1,shuffle=False)
num_epochs = 20
for epoch in range(num_epochs):
  model.train()
  train_loss = 0
  for inputs,outputs in train_loader:
    optimizer.zero_grad()
    prediction = model(inputs)
    loss = bce(prediction,outputs)
    loss.backward()
    optimizer.step()
    train_loss += loss.item()
  train_loss /= len(train_loader)
  model.eval()
  valid_loss = 0
  with torch.no_grad():
    for inputs,outputs in validation_loader:
      prediction = model(inputs)
      loss = bce(prediction,outputs)
      valid_loss += loss.item()
    valid_loss /= len(validation_loader)
  print("epoch -- training loss -- validation loss")
  print(f"epoch {epoch+1} -- {train_loss} -- {valid_loss}")
  print("-"*40)
model.eval()
test_loss = 0
with torch.no_grad():
  for inputs,outputs in test_loader:
    prediction = model(inputs)
    loss = bce(prediction,outputs)
    test_loss += loss.item()
  test_loss /= len(test_loader)
print("Final Test Loss:",test_loss)
new_data = torch.tensor([[4.9,3.1,6.5]])
model.eval()
with torch.no_grad():
  prediction = model(new_data)
  probability = torch.sigmoid(prediction)
print("Predicted class :",probability.item())

Early stopping

In [ ]:
import torch
import torch.nn as nn
from torch.utils.data import random_split,TensorDataset,DataLoader
class ann(nn.Module):
  def __init__(self):
    super().__init__()
    self.fc1 = nn.Linear(3,5)
    self.relu = nn.ReLU()
    self.fc2 = nn.Linear(5,1)
  def forward(self,x):
    x = self.fc1(x)
    x = self.relu(x)
    x = self.fc2(x)
    return x
model = ann()
optimizer = torch.optim.SGD(model.parameters(),lr=0.01)
bce = nn.BCEWithLogitsLoss()
x = torch.tensor([
    [2.5,1.8,3.2],
    [1.2,4.5,2.7],
    [3.6,2.1,5.4],
    [6.3,7.8,1.5],
    [2.8,9.1,4.0],
    [5.4,2.3,1.8],
    [4.1,5.6,2.9],
    [7.2,3.5,6.4],
    [8.5,2.7,1.9],
    [3.3,6.6,5.2],
    [6.8,2.2,4.1],
    [5.7,7.4,3.8],
    [4.6,1.5,6.3],
    [8.4,5.1,2.2],
    [2.9,7.7,5.6]
])
y = torch.tensor([
    [1.0],
    [0.0],
    [1.0],
    [0.0],
    [1.0],
    [0.0],
    [1.0],
    [1.0],
    [0.0],
    [1.0],
    [1.0],
    [0.0],
    [1.0],
    [0.0],
    [1.0]
])
dataset = TensorDataset(x,y)
train, validation, test = random_split(dataset,[11,2,2])
train_loader = DataLoader(train,batch_size=2,shuffle=True)
validation_loader = DataLoader(validation,batch_size=1,shuffle=False)
test_loader = DataLoader(test,batch_size=1,shuffle=False)
num_epochs = 20
best_val_loss = float("inf")
patience = 3
counter = 0
for epoch in range(num_epochs):
  model.train()
  train_loss = 0
  for inputs,outputs in train_loader:
    optimizer.zero_grad()
    prediction = model(inputs)
    loss = bce(prediction,outputs)
    loss.backward()
    optimizer.step()
    train_loss += loss.item()
  train_loss /= len(train_loader)
  model.eval()
  valid_loss = 0
  with torch.no_grad():
    for inputs,outputs in validation_loader:
      prediction = model(inputs)
      loss = bce(prediction,outputs)
      valid_loss += loss.item()
    valid_loss /= len(validation_loader)
  if valid_loss < best_val_loss : # early stopping ---
    best_val_loss = valid_loss
    counter = 0
  else :
    counter += 1
  if counter >= patience :
    print("Early stopping triggered")
    break
  print("epoch -- training loss -- validation loss")
  print(f"epoch {epoch+1} -- {train_loss} -- {valid_loss}")
  print("-"*40)
model.eval()
test_loss = 0
with torch.no_grad():
  for inputs,outputs in test_loader:
    prediction = model(inputs)
    loss = bce(prediction,outputs)
    test_loss += loss.item()
  test_loss /= len(test_loader)
print("Final Test Loss:",test_loss)
new_data = torch.tensor([[4.9,3.1,6.5]])
model.eval()
with torch.no_grad():
  prediction = model(new_data)
  probability = torch.sigmoid(prediction)
print("Predicted class :",probability.item())

epoch -- training loss -- validation loss
epoch 1 -- 0.6334264824787775 -- 0.6936471462249756
----------------------------------------
epoch -- training loss -- validation loss
epoch 2 -- 0.6390014290809631 -- 0.689374566078186
----------------------------------------
epoch -- training loss -- validation loss
epoch 3 -- 0.6255664477745692 -- 0.6857577562332153
----------------------------------------
epoch -- training loss -- validation loss
epoch 4 -- 0.6712841838598251 -- 0.6827192306518555
----------------------------------------
epoch -- training loss -- validation loss
epoch 5 -- 0.6958932479222616 -- 0.6815064549446106
----------------------------------------
epoch -- training loss -- validation loss
epoch 6 -- 0.6649891287088394 -- 0.6760348975658417
----------------------------------------
epoch -- training loss -- validation loss
epoch 7 -- 0.6995346893866857 -- 0.6723468005657196
----------------------------------------
epoch -- training loss -- validation loss
epoch 8 -- 0.6

### **14. Custom Dataset**
USE : To load and preprocess real-world data (CSV, images, text, etc.) so it can be used with PyTorch.

In [ ]:
import pandas as pd
data = pd.read_csv("data.csv")
data.head()

,StudyHours,Attendance,Assignments,Pass
0,2,60,40,0
1,3,65,45,0
2,4,70,50,0
3,5,75,55,0
4,6,80,60,1


In [ ]:
import torch
import torch.nn as nn
from torch.utils.data import random_split,Dataset,DataLoader

class DS(Dataset):
  def __init__(self):
    self.x = torch.tensor(data.drop(columns='Pass').values,dtype=torch.float32)
    self.y = torch.tensor(data['Pass'].values,dtype=torch.float32).unsqueeze(1)
  def __len__(self):
    return len(self.x)
  def __getitem__(self,index):
    return self.x[index],self.y[index]

class ann(nn.Module):
  def __init__(self):
    super().__init__()
    self.fc1 = nn.Linear(3,5)
    self.relu = nn.ReLU()
    self.fc2 = nn.Linear(5,1)
  def forward(self,x):
    x = self.fc1(x)
    x = self.relu(x)
    x = self.fc2(x)
    return x

model = ann()
optimizer = torch.optim.SGD(model.parameters(),lr=0.01)
bce = nn.BCEWithLogitsLoss()

dataset = DS()
train,valid,test = random_split(dataset,[0.8,0.1,0.1])
train_loader = DataLoader(train,batch_size=3,shuffle=True)
valid_loader = DataLoader(valid,batch_size=1,shuffle=False)
test_loader = DataLoader(test,batch_size=1,shuffle=False)

num_epochs = 20
for epoch in range(num_epochs):

  model.train()
  train_loss = 0
  for inputs,outputs in train_loader:
    optimizer.zero_grad()
    prediction = model(inputs)
    loss = bce(prediction,outputs)
    loss.backward()
    optimizer.step()
    train_loss += loss.item()
  train_loss /= len(train_loader)

  model.eval()
  valid_loss = 0
  with torch.no_grad():
    for inputs,outputs in valid_loader:
      prediction = model(inputs)
      loss = bce(prediction,outputs)
      valid_loss += loss.item()
  valid_loss /= len(valid_loader)

  print(f"epoch {epoch+1} : Training_loss {train_loss}, Validation_loss {valid_loss}")
print("-"*30)

model.eval()
test_loss = 0
with torch.no_grad():
  for inputs,outputs in test_loader:
    prediction = model(inputs)
    loss = bce(prediction,outputs)
    test_loss += loss.item()
test_loss /= len(test_loader)
print(f"Test_loss {test_loss}")

model.eval()
cl = 0
x = torch.tensor([[2,60,40]],dtype=torch.float32)
with torch.no_grad():
  prediction = model(x)
  probability = torch.sigmoid(prediction)
if probability>=0.5:
  cl = 1
else :
  cl = 0
print(f"Predicted Class for {x} is {cl}")

epoch 1 : Training_loss 4.435379736125469, Validation_loss 0.7434993584950765
epoch 2 : Training_loss 0.6444925144314766, Validation_loss 0.7381571928660074
epoch 3 : Training_loss 0.6391046941280365, Validation_loss 0.734820028146108
epoch 4 : Training_loss 0.6366429105401039, Validation_loss 0.735563854376475
epoch 5 : Training_loss 0.6359522193670273, Validation_loss 0.7229176958401998
epoch 6 : Training_loss 0.6299837678670883, Validation_loss 0.7196280558904012
epoch 7 : Training_loss 0.629742905497551, Validation_loss 0.7215674519538879
epoch 8 : Training_loss 0.6366385668516159, Validation_loss 0.7529865701993307
epoch 9 : Training_loss 0.618811123073101, Validation_loss 0.6766020655632019
epoch 10 : Training_loss 0.6436053663492203, Validation_loss 0.7717047333717346
epoch 11 : Training_loss 0.6331338360905647, Validation_loss 0.7741272250811259
epoch 12 : Training_loss 0.6319340839982033, Validation_loss 0.7765091856320699
epoch 13 : Training_loss 0.6309186369180679, Validatio

### **15. Save Models**
RECOMMENDED BY PYTORCH TO SAVE PARAMETERS

torch.save(model.state_dict(),"filename.pth")

model1.load_state_dict(torch.load("filename.pth"))

In [ ]:
print(model.state_dict())

OrderedDict({'fc1.weight': tensor([[ 0.5059,  0.2661, -0.4374],
        [ 0.1718,  0.1376, -0.5260],
        [ 0.3956, -0.0303, -0.0194],
        [ 0.1721,  0.1787, -0.4775],
        [ 0.3154, -0.1088, -0.5510]]), 'fc1.bias': tensor([ 0.0166, -0.2371,  0.0626,  0.0370, -0.0321]), 'fc2.weight': tensor([[-0.0806, -0.2077,  0.1987, -0.0497, -0.3627]]), 'fc2.bias': tensor([0.4549])})


In [ ]:
torch.save(model.state_dict(),"passorfailann.pth")

In [ ]:
model1 = ann()
print(model1.state_dict())

OrderedDict({'fc1.weight': tensor([[-0.4919, -0.2565,  0.5001],
        [ 0.0245, -0.3071, -0.0811],
        [ 0.3943,  0.4373, -0.0702],
        [ 0.5211,  0.3492,  0.0070],
        [-0.1316,  0.5628, -0.3312]]), 'fc1.bias': tensor([-0.0667, -0.5100, -0.4991,  0.4628,  0.2807]), 'fc2.weight': tensor([[ 0.1667,  0.2708, -0.1621,  0.4355, -0.1000]]), 'fc2.bias': tensor([0.4390])})


In [ ]:
model1.load_state_dict(torch.load("passorfailann.pth"))
print(model1.state_dict())

OrderedDict({'fc1.weight': tensor([[ 0.5059,  0.2661, -0.4374],
        [ 0.1718,  0.1376, -0.5260],
        [ 0.3956, -0.0303, -0.0194],
        [ 0.1721,  0.1787, -0.4775],
        [ 0.3154, -0.1088, -0.5510]]), 'fc1.bias': tensor([ 0.0166, -0.2371,  0.0626,  0.0370, -0.0321]), 'fc2.weight': tensor([[-0.0806, -0.2077,  0.1987, -0.0497, -0.3627]]), 'fc2.bias': tensor([0.4549])})


In [ ]:
### not recomended -- saving a model directly, so pytorch recommend to save parameters
# torch.save(model,"model.pth")
# model = torch.load("model.pth")

### Save model checkpoint after every epoch (so training can resume if power goes off or execution stops)
for epoch in range(num_epochs):

  torch.save(model.state_dict(), "ann_model.pth")

### **16. Evaluation Metrics**


```
model.eval()

y_true = []

y_pred = []

with torch.no_grad():

    for inputs, outputs in test_loader:

        prediction = model(inputs)

        # Convert prediction if needed
        # Binary  -> sigmoid + threshold -- probability = torch.sigmoid(prediction) -- predicted = (probability >= 0.5).int()
        # Multi   -> argmax
        # Regression -> use prediction directly

        y_true.extend(outputs.numpy())

        y_pred.extend(predicted.numpy())

# Choose any metric you want
accuracy_score(...)
precision_score(...)
recall_score(...)
f1_score(...)
confusion_matrix(...)
mean_absolute_error(...)
mean_squared_error(...)
rmse = np.sqrt(mse)
r2_score()


```