In [1]:
import numpy as np
import pandas as pd

# **Feature Engineering**

## **Label Encoding**

### Purpose : Convert categorical text values into numbers.

## Working:
### 1. Find unique categories
### 2. Sort them alphabetically
### 3. Assign numbers from 0 to n-1

### Example:Blue,Green,Red -> Blue=0, Green=1, Red=2 (Input : Requires 1D Array)

### Advantage :Simple and easy.

### Disadvantage : May create false ordering.

##Example:

### Blue  → 0, Green → 1, Red   → 2

### Model may think : Red > Green > Blue

### Best For : Ordered categories
### Like : Low → 0, Medium → 1, High   → 2

In [2]:
from sklearn.preprocessing import LabelEncoder
data = ['low','high','medium','low','high']
le = LabelEncoder()
encoder = le.fit_transform(data)
print(encoder)
decoder = le.inverse_transform(encoder)
print(decoder)

[1 0 2 1 0]
['low' 'high' 'medium' 'low' 'high']


## **One-Hot Encoding**

### Purpose : Convert categories into binary columns.

## Example:
### Red, Blue, Green

### ↓

### Blue Green Red

### 0    0     1

###1    0     0

###0    1     0

## Input:
###Requires 2D Array



### Why? Avoid false ordering.

### Best For : Unordered Categories

### Examples : Color, City, Country

### Scikit-Learn : OneHotEncoder()

### Pandas : pd.get_dummies()

### Disadvantage : Creates many columns (High Dimensionality)

In [3]:
from sklearn.preprocessing import OneHotEncoder
data = [['Red'],['red'],['Green']]
oe = OneHotEncoder()
encoder = oe.fit_transform(data)
print(encoder.toarray())
decoder = oe.inverse_transform(encoder)
print(decoder)

[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
[['Red']
 ['red']
 ['Green']]


## **Standard Scaler**

### Purpose : Scale numerical features.

### Formula : z = (x - mean) / standard deviation

### Input Required : 2D array

### Goal :  is to force your data to have a mean of 0 and a standard deviation of 1.


### Use For : KNN, SVM, PCA (because they deal with distance and magnitude)

### Not Usually Needed : Decision Tree, Random Forest

### Do Not Scale : Names, Cities, Colors, Countries

In [4]:
from sklearn.preprocessing import StandardScaler

age = np.array([20,25,30])
salary = np.array([20000,28000,32000])

age = age.reshape(-1,1) # reshape(-1,1) converts 1d to 2d
salary = salary.reshape(-1,1) # as standard scaler requires 2darray as input

print("Age :", age)
print("Salary :",salary)

scaler = StandardScaler()
scaled_age = scaler.fit_transform(age)
print("Scaled Age :",scaled_age)
scaled_salary = scaler.fit_transform(salary)
print("Scaled Salary :",scaled_salary)

Age : [[20]
 [25]
 [30]]
Salary : [[20000]
 [28000]
 [32000]]
Scaled Age : [[-1.22474487]
 [ 0.        ]
 [ 1.22474487]]
Scaled Salary : [[-1.33630621]
 [ 0.26726124]
 [ 1.06904497]]


## Before Scaling

### Age      : 20,25,30
### Salary   : 20000,28000,32000
### Salary dominates.( in algorithms like KNN,SVM,KMEANS,PCA )

## After Scaling

### Age      : -1.22,0,1.22
### Salary   : -1.33,0,1.06
### Both contribute equally.

### Standard Scaler is done : To Ensure equal feature contribution

## **Mini Max Scaler**
### A scaling technique that transforms values into a fixed range, usually : 0 to 1

### Purpose : Scale numerical features.

### Required Input : 2D Array

### Result : Minimum Value = 0, Maximum Value = 1

### Output Range : 0 to 1

### Advantages : Easy to understand, Values stay between 0 and 1

### Used in : image processing, deep learning , KNN etc

In [5]:
from sklearn.preprocessing import MinMaxScaler

age = np.array([20,25,30])
salary = np.array([20000,28000,32000])

age = age.reshape(-1,1) # reshape(-1,1) converts 1d to 2d
salary = salary.reshape(-1,1) # as min max scaler requires 2darray as input

print("Age :", age)
print("Salary :",salary)

scaler = MinMaxScaler()
scaled_age = scaler.fit_transform(age)
print("Scaled Age :",scaled_age)
scaled_salary = scaler.fit_transform(salary)
print("Scaled Salary :",scaled_salary)

Age : [[20]
 [25]
 [30]]
Salary : [[20000]
 [28000]
 [32000]]
Scaled Age : [[0. ]
 [0.5]
 [1. ]]
Scaled Salary : [[0.        ]
 [0.66666667]
 [1.        ]]


## **Feature Selection**

### Purpose : Keep important features, Remove unimportant features

### Benefits : Faster Training, Less Overfitting, Better Performance

## Methods:
### 1. Correlation : df.corr()

### 2. Feature Importance : model.feature_importances_

### 3. SelectKBest

In [6]:
df = pd.DataFrame({
    'ID':[100,99,75],
    'Age':[20,25,30],
    'Salary':[25000,35000,45000],
    'Marks':[70,80,90]
})
y = pd.Series([0,1,1])

In [7]:
# method 1 - using corr() of pandas
df['result'] = y
print(df.corr())

              ID       Age    Salary     Marks    result
ID      1.000000 -0.883148 -0.883148 -0.883148 -0.530281
Age    -0.883148  1.000000  1.000000  1.000000  0.866025
Salary -0.883148  1.000000  1.000000  1.000000  0.866025
Marks  -0.883148  1.000000  1.000000  1.000000  0.866025
result -0.530281  0.866025  0.866025  0.866025  1.000000


In [8]:
# method 2 - using feature_importances_ of decision tree/random forest
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier()
x = df.drop(columns=['result'])
model.fit(x,y)
print(model.feature_importances_)

[1. 0. 0. 0.]


In [9]:
# method 3 - using SelectkBest
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_classif
selector = SelectKBest(score_func=f_classif,k=2) # for regression we use f_regression
new = selector.fit_transform(x,y)
print(new)
selected_columns = x.columns[selector.get_support()] # check selected columns
print(selected_columns)

[[25000    70]
 [35000    80]
 [45000    90]]
Index(['Salary', 'Marks'], dtype='object')


## **PCA ( Principal Component Analysis )**

### Type : Dimensionality Reduction

### Purpose : Reduce number of features

### Pre required : StandardScaler required before we actually implement PCA

### Feature Selection : Removes columns

### PCA : Creates new columns

### New Features : PC1, PC2, PC3

### Workflow : StandardScaler() -> PCA() -> fit_transform()

### Important : PCA(n_components=n), explained_variance_ratio_

### Benefits : Faster Training, Less Memory, Reduced Overfitting

In [10]:
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
data = [[20,20000,20],[25,25000,75],[30,30000,80]]
scaler = StandardScaler()
scaled_data = scaler.fit_transform(data)
pca = PCA(n_components=2)
new = pca.fit_transform(scaled_data)
print(new)
print(pca.explained_variance_ratio_) # to check percentage of info retained

[[-2.22550331 -0.18935903]
 [ 0.3454212   0.50658074]
 [ 1.88008211 -0.31722171]]
[0.95632106 0.04367894]


### PC1 : Maximum information (variance)

### PC2 : Second highest information

### PC3 : Third highest information and so on